version: '3'

services:
  splunk:
    image: splunk/splunk:latest
    ports:
      - 8000:8000
      - 8088:8088
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_PASSWORD: supersecret
    volumes:
      - ./splunk/search.conf:/opt/splunk/etc/apps/search/local/inputs.conf
      - ./splunk/http.conf:/opt/splunk/etc/apps/splunk_httpinput/local/inputs.conf

  uf:
    image: splunk/universalforwarder:latest
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_PASSWORD: supersecret
    volumes:
      - nginx-logs:/var/log/nginx
      - ./universal-forwarder/inputs.conf:/opt/splunkforwarder/etc/apps/search/local/inputs.conf
      - ./universal-forwarder/outputs.conf:/opt/splunkforwarder/etc/system/local/outputs.conf

  fluentd:
    build:
      context: fluentd
      dockerfile: Dockerfile.fluentd
    command:
      - fluentd
      - -c
      - /fluentd/etc/fluentd.conf
    volumes:
      - nginx-logs:/var/log/nginx
      - ./fluentd/fluentd.conf:/fluentd/etc/fluentd.conf

  nginx:
    image: nginx:stable
    ports:
      - 8080:80
    volumes:
      - nginx-logs:/var/log/nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  nginx-logs:
